# Generated by Django 5.0.1 on 2024-02-21 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[('Perishable', 'Easily goes bad'), ('Non Perishable', 'Stays for long')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=25)),
                ('destination', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_id', models.CharField(max_length=8, unique=True)),
                ('Capacity', models.IntegerField()),
                ('Type', models.CharField(max_length=20)),
                ('refrigerated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('related_model_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.register')),
            ],
        ),
    ]
